"""Agregar columna is_active a users

Revision ID: 4cdd7974b8d2
Revises: 7d68d5c0cbb1
Create Date: 2026-09-17 09:30:14.365879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdd7974b8d2'
down_revision: Union[str, Sequence[str], None] = '7d68d5c0cbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
