print("2")
print(2)
print(0o123)
print(0x123)
print(2.5)
print(-0.4)
print(.4)
print(4.)
print(1.23e10)
print(1e12)
print(0.0000000000000000000001)
print("¡Hey, muy buenas a todos, \"guapísimos, aquí Vegetta 777\" ")
print('Este era mas facil de "hacer :/"')
print('I\'m fine.')
print(True > False)
print(True < False)
print(True == False)
print(True != False)
print(True >= False)
print(True <= False)
print(True and False)
print(True or False)
print(not True)
print(not False)
print(1 + 2)
print(True + 2)
print(1 + False)
print((True and False) or (True or False))
print((True and False) and (True or False))
print(((True and False) and (True or False) or (True and False)) or (True or False))
print("estoy \"aprendiendo\" sobre Python y d'aquel tema basico sobre literales y cadenas como: " +str(True or False), 2+2, 4e9, 0x123, 0o123, "y mas cosas que se me ocurran")